---
name: "MediathekViewMover"
guid: "18C3F73B-DC8F-4170-A8D0-04EC1A65AD6A"
version: "0.0.1.6"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Ordnet MediathekView-Downloads sauber für Jellyfin ein."
description: >
  MediathekViewMover ist ein Plugin für Jellyfin, das heruntergeladene Inhalte aus MediathekView automatisch in ein sauberes und einheitliches Format bringt. Es benennt Serienepisoden und Filme korrekt um, erkennt und gruppiert Untertitel sowie alternative Audiospuren, und legt alles ordentlich im Jellyfin-Verzeichnis ab. So wird dein Medienarchiv nicht nur aufgeräumter, sondern auch kompatibler und übersichtlicher – ganz ohne manuelles Nachbearbeiten.

category: "General"
owner: "Minegamer06"
artifacts:
  - "Jellyfin.Plugin.MediathekViewMover.dll"
  - "FFMpegCore.dll"
  - "Instances.dll"
changelog: >-
  Update build.yaml

  Merge pull request #1 from Minegamer06/dev

  Loggin bei Sprachauflösung erweitert

  Update build.yaml and manifest.json for release version 0.0.1.4

  Merge branch 'master' of https://github.com/Minegamer06/jellyfin-plugin-MediathekViewMover

  AudioDescription sollte immer unten sein, ausderm kann es sonst bugs geben
