---
name: "MediathekViewMover"
guid: "18C3F73B-DC8F-4170-A8D0-04EC1A65AD6A"
version: "0.0.1.2"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Ordnet MediathekView-Downloads sauber für Jellyfin ein."
description: >
  MediathekViewMover ist ein Plugin für Jellyfin, das heruntergeladene Inhalte aus MediathekView automatisch in ein sauberes und einheitliches Format bringt. Es benennt Serienepisoden und Filme korrekt um, erkennt und gruppiert Untertitel sowie alternative Audiospuren, und legt alles ordentlich im Jellyfin-Verzeichnis ab. So wird dein Medienarchiv nicht nur aufgeräumter, sondern auch kompatibler und übersichtlicher – ganz ohne manuelles Nachbearbeiten.

category: "General"
owner: "Minegamer06"
artifacts:
  - "Jellyfin.Plugin.MediathekViewMover.dll"
  - "FFMpegCore.dll"
  - "Instances.dll"
changelog: >-
  FFMpeg Pfad sollte richtig extrahiert werden

  Update manifest.json

  Update build.yaml and manifest.json for release version 0.0.1.0

  FFMpegCore muss mit Kopiert werden

  Erster Testrelease
