---
name: "MediathekViewMover"
guid: "18C3F73B-DC8F-4170-A8D0-04EC1A65AD6A"
version: "0.0.0.1"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "Minegamer06"
artifacts:
- "Jellyfin.Plugin.MediathekViewMover.dll"
changelog: >
  changelog
